### ISSUE TITLE
GitHub Mentions

### ISSUE THREAD

**Issue by gcanti** [suddenlyGiovanni/resume#94]
@suddenlyGiovanni FYI, I'm receiving a lot of emails because in many commits like this one https://github.com/suddenlyGiovanni/resume/commit/b32050274eaabd092e9b78c98b84f57a8fdf8362, you are mentioning me

**Comment by suddenlyGiovanni** [comment]
Sorry, my bad.
I have been using the schema's change log in my commit descriptions and probably the citations have been interpreted by gh as mentions! 🤦‍♂️.


Thx for let me know, I'll address it immediately.
